### ISSUE TITLE
USB Error -63

### ISSUE THREAD

**Issue by execOQ** [foxlet/bootra1n#101]
Hello, when I try to jailbreak my iphone SE 1st generation IOS 14.0.1 I get the error "USB error -63". Do you know what the problem is?

**Comment by walylou0** [comment]
Same problem with an iPhone SE iOS 14.0.1

**Comment by DEALWITHIT199** [comment]
Try using [Odysseyn1x](https://github.com/raspberryenvoie/odysseyn1x) or [Checkn1x](asineth.gq/checkn1x.html). There just desame as bootra1n but better. I prefer using Odysseyn1x first. Thank you and have a great day!

**Comment by execOQ** [comment]
@DEALWITHIT199 I will definitely try Odysseyn1x. I have already used Checkn1x, Bootra1n and Checkra1n, but none have been able to do a jailbreak on my device. Thanks for your help, have a nice day.

**Comment by DEALWITHIT199** [comment]
> @DEALWITHIT199 I will definitely try Odysseyn1x. I have already used Checkn1x, Bootra1n and Checkra1n, but none have been able to do a jailbreak on my device. Thanks for your help, have a nice day.

Glad to help you laggerbonni!
