### ISSUE TITLE
Cant get jailbreak. Error -1 (Error getting device info)

### ISSUE THREAD

**Issue by hajimura** [foxlet/bootra1n#105]
Hello everyone. I have an error while trying to install jailbreak. Error getting device info (-1)
How can i solve this problem? Help, please
iPhone SE 2020 with iOS 13.6 installed

**Comment by cnrkuo** [comment]
checkra1n DOES NOT support iPhone SE actually...
'Cause devices using A12 Bionic or later's CPU does NOT have the checkm8 loophole --- The loophole that checkra1n used.

**Comment by hajimura** [comment]
Oh, already thought nobody wouldn't ask on my question. Bad news, unfortunately. Anyway, thanks

**Comment by cnrkuo** [comment]
Oh, actually, you can use Odessey tool if you're on iOS 13.0 to 13.7~ @theshadowz

**Comment by hajimura** [comment]
Oh, thanks a lot for the answer. I'll try this soft
