### ISSUE TITLE
Bypass checkra1n error on Ipad 5 wifi ios 14.1

### ISSUE THREAD

**Issue by CNitro** [foxlet/bootra1n#111]
I tried on 4 pc with Windows(Bootra1n) and linux, 3 diferent original Apple cables and check/unchecked the safe mode option, verbose boot option and i get error -77 and-79 everytime on my ipad 5 wifi ios 14.1 with activation lock.

**Comment by Treegardener** [comment]
this was due to an issue in checkra1n 0.11.0 and was fixed by the new release 0.12.0.
I tried it by myself successfully with an ipad 5 at 14.1.

You have to wait for Bootra1n to include checkra1n 0.12.0 or run it directly on a bare metal linux installation.
