### ISSUE TITLE
Other File Download

### ISSUE THREAD

**Issue by rnmeow** [foxlet/bootra1n#127]
https://mega.nz/file/1qQzgApD#ZA9CRkl3FCeHlok39kXTKRXEwh0KQPoJajVKMTz0ZzQ

**Comment by cnrkuo** [comment]
It may not update anymore maybe...

Download 0.12.0 [Here?](https://mega.nz/file/1qQzgApD#ZA9CRkl3FCeHlok39kXTKRXEwh0KQPoJajVKMTz0ZzQ)

**Comment by kartana** [comment]
Yeah, I am not keen on downloading random zip files... Where is this from?

**Comment by knipknaps** [comment]
> Yeah, I am not keen on downloading random zip files... Where is this from?

**Yep i am with you, where is this coming from?**
