### ISSUE TITLE
graphics safe mode

### ISSUE THREAD

**Issue by Quinten0508** [foxlet/bootra1n#23]
Hey, could you please add the option:
Boot (graphics safe mode)
When running bootra1n x64 on my pc, the graphics are all messed up and the command line is unreadable. I had the same issue with an ubuntu live usb, and when selecting graphics safe mode, the issue stopped.

**Comment by AImXOo0o** [comment]
Hello. Same problem. Cant read anything. Thank you! :)

**Comment by foxlet** [comment]
This option has been added in bootra1n 0.10.1.
