### ISSUE TITLE
Bootra1n weird screen funny writings 

### ISSUE THREAD

**Issue by Al-Rashed** [foxlet/bootra1n#27]
please see the video I tried different PCs, different USBs, different images, disabled Secure and Fast Boot

![Untitled](https://user-images.githubusercontent.com/62574966/77372021-1e4ea980-6d7e-11ea-815b-6cd1b70afdf1.jpg)

**Comment by AImXOo0o** [comment]
Same problem :o

**Comment by Al-Rashed** [comment]
did you found a solution ?

**Comment by AImXOo0o** [comment]
Sadly no. But I didn't try it anymore.
What is your graphic setup?
I thought that the WQHD Display is the problem.

**Comment by foxlet** [comment]
Try the "Graphics Safe" option in 0.10.1.
