### ISSUE TITLE
[Suggestion] add info that bootra1n works on DVD

### ISSUE THREAD

**Issue by infinitephantasm** [foxlet/bootra1n#28]
hello, did some testing out of boredom recently and decided to see if bootra1n worked on a DVD since my multiboot USB was having issues (YUMI + bootra1n = not work, at least in GRUB unlisted)

surprisingly enough, it worked on my ATV4 (although giving error -77. didn't really matter since it still did the jailbreak just fine). i don't have other devices to test with, but from what i can tell, bootra1n works on DVD. it may also work on CD but i haven't tested that.

figured it'd be nice to have this known, even if no one really uses boot CDs/DVDs much anymore

**Comment by TonnyNoguera** [comment]
**English:**
Try booting it as a Linux void and in FAT32 format (that was the only way bootra1n worked on my multibootUSB)


**Español:**
Intenta bootearlo como un void Linux y en formato FAT32 (esa fue la única manera en la qué me funciono bootra1n en mi multibootUSB)

**Comment by foxlet** [comment]
This has been added to the README. Thanks!
