### ISSUE TITLE
13.4 checkra1n 0.10.0

### ISSUE THREAD

**Issue by aksneo** [foxlet/bootra1n#29]
hi.
can you update your project?
https://t.co/lZRIDrfUNE?amp=1

**Comment by haider1977** [comment]
Please bootra1n 0.10.0

**Comment by Ivofcalmeida** [comment]
Greatly appreciated if you can update as some of use can only use checkra1n through Bootra1n.

**Comment by foxlet** [comment]
This is only for macOS, it's not compatible with bootra1n as it is Linux based.

**Comment by haider1977** [comment]
Thankful 


مُرسل من بريد Yahoo لجهاز iPhone


بتاريخ الخميس, آذار 26, 2020, 9:49 م، Foxlet <notifications@github.com> كتب:




This is only for macOS, it's not compatible with bootra1n as it is Linux based.

**Comment by aksneo** [comment]
we will waiting your good news

**Comment by Ivofcalmeida** [comment]
Just released new version. 
https://checkra.in/#release
Thanks for updating

**Comment by foxlet** [comment]
It has been updated, thanks for waiting!
