### ISSUE TITLE
Unable to boot on a microsoft surface pro 7

### ISSUE THREAD

**Issue by nate-moo** [foxlet/bootra1n#3]
when i used etcher to write the ISO to the drive i try and boot but it just glitches out and sends me to windows even after selecting to boot into the USB thumbstick

**Comment by foxlet** [comment]
You may need to disable Secure Boot in your BIOS settings before being able to boot the drive.

**Comment by nate-moo** [comment]
> 
> 
> You may need to disable Secure Boot in your BIOS settings before being able to boot the drive.

Yea, when i actually went into bios to properly boot into the thumbstick (not the windows bootloader) it bugged me about secure boot, so i disabled it and it works. just the bitlocker thing will get annoying whenever i restart into linux

**Comment by suncreations** [comment]
@nate-moo I know you’ve closed this ticket. I know that you managed to boot bootra1n but did you successfully jailbreak with Checkra1n? I tried using Surface Pro 2 but as soonest the device is put in DFU computer stops seeing device.
