### ISSUE TITLE
Checkra1n 10

### ISSUE THREAD

**Issue by amrit634** [foxlet/bootra1n#34]
Please update bootra1n for 13.4

**Comment by 7OU** [comment]
That's something to do with checkra1n, bootra1n is just a Void Linux ISO to use checkra1n without installing Linux.

**Comment by nicolas17** [comment]
checkra1n 0.10 added support for 13.4. This ticket is about making bootra1n include the newer checkra1n.

**Comment by 7OU** [comment]
Only until now can you use 0.10 on linux 0.10.0 was mac only 0.10.1 is linux as well.

**Comment by foxlet** [comment]
This build will be out in a bit. :)
