### ISSUE TITLE
[HINT+REQUEST] Definitive Fix for Error -71 on bootra1n

### ISSUE THREAD

**Issue by yursnake** [foxlet/bootra1n#35]
Hi @foxlet ! First of all, thanks for your tool (bootra1n).
Second, many people are getting error 71 while using bootra1n.
https://github.com/foxlet/bootra1n/issues/6
https://github.com/foxlet/bootra1n/issues/8

This is the definitive solution:
https://urukrama.wordpress.com/2009/01/27/usb-drive-not-recognised-error-71/
We could solve just adding the following line to "/etc/modprobe.d/options:"
`	options usbcore use_both_schemes=y
`
Could you apply this fix on the linux kernel of next versions of bootra1n? please

**Comment by foxlet** [comment]
This will added as the "USB Safe" option in 0.10.1.
