### ISSUE TITLE
I Didn't get the ISO file

### ISSUE THREAD

**Issue by DeadlyMars** [foxlet/bootra1n#36]
i didn't get the file 
the zip inside it are boot, liveOS and [BOOT]
Please help I want to jailbreak my iphone!!!

**Comment by DeadlyMars** [comment]
![2020-04-08](https://user-images.githubusercontent.com/63337694/78757434-2bc28100-7985-11ea-8ee8-5b207682530b.png)

**Comment by nicolas17** [comment]
That's not a zip, you tried to extract the iso. Use it directly without extracting it.
