### ISSUE TITLE
A7 Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [foxlet/bootra1n#40]
Yes, A7 isn't fixed..........

Everybody says unplug and plug device on right before trigger step. ok i did then checkra1n boots my device and said usb error -77 then I tried usb safe mod then i did again all step and said error -63 this time. God damn i wanna jailbreak my deviceeee.....

**Comment by JesseB0rn** [comment]
Check you run it with sudo. Also, try removing your passcode temporarily. USB -77 doesn't stop the jailbreak process, most times it still completes successful.

**Comment by CanerKaraca23** [comment]
> Check you run it with sudo. Also, try removing your passcode temporarily. USB -77 doesn't stop the jailbreak process, most times it still completes successful.

I already removed my password. yes USB error -77 doesn't stops jailbreak process, my device starts but checkra1n logo doesn't appears I2m waiting 2-5 minutes.
