### ISSUE TITLE
task checkra1n blocked for more than 122 seconds.

### ISSUE THREAD

**Issue by Avellea** [foxlet/bootra1n#69]
Hey there. Trying to use this awesome project. Great work! However, I'm running into the same issue in issue #32. I tried the workaround below, but that resulted in the following picture. 

https://imgur.com/DgmW9dS

I'd love to be able to jailbreak my iPad Air 1 using this, as there is no Windows alternative yet. Thanks!

> > iPhone 5s support fixed now.
> 
> How

When you see the 122 second timeout, from the phone side unplug and immediately plug the lighting port back in. On the screen you should see the jailbreak happening then. Then the icon will be waiting on the screen to install cydia. 

_Originally posted by @141 in https://github.com/foxlet/bootra1n/issues/32#issuecomment-612525037_

**Comment by 141** [comment]
Try different cables, especially worn and old cables may not work.

**Comment by Avellea** [comment]
> Try different cables, especially worn and old cables may not work. 

Issue still persists after buying a new cable. Tested on new OEM and new aftermarket.

**Comment by Avellea** [comment]
Closing as developer seems to have stopped supporting this project.
