### ISSUE TITLE
iPadOS 13.6.1 Not Compatible

### ISSUE THREAD

**Issue by Fervencyy** [foxlet/bootra1n#82]
Pretty self-explanatory. I'm not sure if this is intentional but from what I've seen regular Checkra1n works on devices running 13.6.1. Is iPadOS just a completely different issue?

**Comment by Mattthewlol** [comment]
try using the use unsupported ios firmware option

**Comment by Fervencyy** [comment]
I should have thought of that lol. Unfortunately, it returns usbmux error -92 and running in safe mode has no effect. I guess i'm stuck

**Comment by Mattthewlol** [comment]
Thats just weird the opposite happens to me. If I don't use safe mode error -92 shows up but when I get no errors.

**Comment by bahaahani** [comment]
Checkra1n works for me on ios 13.6.1 on iPad pro 2017 12.9" Yet sometimes it is unresponsive,  You will definitely face a lot of random stutters. I don't recommend using it on ios 13.6.1 until it gets official support.

**Comment by Fervencyy** [comment]
Umm so I just checked and the checkra1n app was apparently on my iPad the whole time? Even though I’ve been getting errors each time? Shoot, I’m not complaining.
