### ISSUE TITLE
Stuck at booting on iphone but bootra1n says its completed

### ISSUE THREAD

**Issue by Mattthewlol** [foxlet/bootra1n#83]
Im on iphone 6s and on ios 13.7. The first time I tried bootra1n everything was fine. Today I downloaded a tweak that just messed up my device so I hard reset it and checkra1n got deleted. So I went back into bootra1n and tried rejailbreaking but it wouldn't work.   On my laptop it says that the jailbreaking was done but on my iphone it was stuck on the checkra1n logo and it just said booting. It would just be like that for a few minutes. Then when the device finally boot up my phone isnt jailbroken and checkra1n isn't there. I've run the process many times,deleted and redownloaded but nothing works. Now the cydia app is stuck on my phone and crashes when I open it.  The settings I used are use unsupported ios firmwares and safe boot. Not my picture but it looked something like this (Edit: I fixed this issue by restoring my iphone and then jailbreaking again)
![68986832-80daea80-085e-11ea-9eff-f075583e79a9](https://user-images.githubusercontent.com/70993374/92551324-9157b980-f212-11ea-8add-6e960ff4c706.png)

**Comment by PRinceBhai** [comment]
So issue closed?

**Comment by Mattthewlol** [comment]
sorry im still kinda new to github im not really that familiar with the features.
