### ISSUE TITLE
Update Bootra1n

### ISSUE THREAD

**Issue by DEALWITHIT199** [foxlet/bootra1n#90]
Hi creators of bootra1n. can I kindly ask to update bootra1n to 0.11.0 since checkra1n has recently updated to 0.11.0.
Thank you!❤ (This is not an issue)

**Comment by foxlet** [comment]
Test images have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

**Comment by iMAHMOD** [comment]
It's 0.10.2 not 11

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

Ummm.. just in case what happens if something goes wrong with my phone? my iDevice is iPhone 6s 13.7 jailbroken by bootra1n checkra1n.

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

Which is the 64bit iso file because theres x86 64 and i686? Its confusing😅

**Comment by iMAHMOD** [comment]
> > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> 
> 
> 
> Which is the 64bit iso file because theres x86 64 and i686? Its confusing😅

X86 64

**Comment by coolkid5613** [comment]
How do I update kernel I’ve been having problems trying to figure this out! Thanks

**Comment by coolkid5613** [comment]
> > > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> > 
> > 
> > Which is the 64bit iso file because theres x86 64 and i686? Its confusing😅
> 
> X86 64

How do I update the kernel lol

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

ok I'm about to try it now, hope it successfully works!

**Comment by coolkid5613** [comment]
> > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> 
> ok I'm about to try it now, hope it successfully works!

Tell me if it does and how you updated the kernel please! Thanks

**Comment by DEALWITHIT199** [comment]
> > > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> > 
> > 
> > ok I'm about to try it now, hope it successfully works!
> 
> Tell me if it does and how you updated the kernel please! Thanks

wdym update kernel???

**Comment by coolkid5613** [comment]
I’m 

> > > > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> > > 
> > > 
> > > ok I'm about to try it now, hope it successfully works!
> > 
> > 
> > Tell me if it does and how you updated the kernel please! Thanks
> 
> wdym update kernel???

I’m his post he says update kernel and when I went to launch bootra1n from the voidlinux menu it says update kernel I couldn’t figure it out

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

Getting this error, Please fix.
![Uploading 2FE4186B-211D-43D5-9CBD-22CD87444C26.jpeg…]()

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

I'm trying to Jailbreak my Newly updated iOS 14.0 iPhone 6s and I got this error, Please fix.
![Bootra1n Checkra1n Error](https://user-images.githubusercontent.com/57556087/93892838-8c6d2c80-fd1f-11ea-9f73-b96e8d960dec.jpg)

**Comment by DEALWITHIT199** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

JAILBREAK IOS 14.0 SUCCESSFULLY WORKED! No issues so far! Error doesn’t come up when “Safe Mode” is on/enabled.
![D356BDD6-8F0F-4E58-A1B4-FABE4D87E319](https://user-images.githubusercontent.com/57556087/93895670-ac521f80-fd22-11ea-91fc-577ef0ac6f0e.png)
![331BEEEC-1356-41FB-9E9F-D109C70C3488](https://user-images.githubusercontent.com/57556087/93895695-b1af6a00-fd22-11ea-897d-878201db6290.png)
![8F05F9D4-15A5-4501-A5F9-E23360B22C84](https://user-images.githubusercontent.com/57556087/93895696-b2480080-fd22-11ea-9915-c352a0a0aae8.png)
![1F87FCAC-506A-4FE2-A8A2-E5CC40B13E47](https://user-images.githubusercontent.com/57556087/93895698-b2e09700-fd22-11ea-9615-745976138a1f.png)
![AAE06B35-ED07-4E6D-9E13-4A05D28B7013](https://user-images.githubusercontent.com/57556087/93895703-b411c400-fd22-11ea-9e04-d6492eb9a2c2.png)

**Comment by trieuvyy** [comment]
> Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0

Thank you, I have successfully jailbroken with my iPhone 6s iOS 14.0.
I have tried it again until the 5th time it was successful. Before that I also saw error codes -5, -63, and -77.

**Comment by DEALWITHIT199** [comment]
> > Test ISOs have been posted on https://github.com/foxlet/bootra1n/releases/tag/0.11.0
> 
> Thank you, I have successfully jailbroken with my iPhone 6s iOS 14.0.
> I have tried it again until the 5th time it was successful. Before that I also saw error codes -5, -63, and -77.

To avoid errors do the following:
Always "Turn off" your passcode before Jailbreaking
Insert the bootable USB Drive into the 2.0 USB Slot
Turn off your Wifi/Turn on Airplane Mode (optional in case still getting errors)
Then lastly.... do the steps properly
Note: if getting error "Hmm devhelper exited unexpectedly. Exiting." Turn on Safe mode before Jailbreaking.
Ty and Have a Great Day!

**Comment by Hackinman120** [comment]
What should I do if bootrain does not recognize the device?
I've changed USB ports, changed iPhones, and it hasn't been recognized.

**Comment by ImranDoet** [comment]
> What should I do if bootrain does not recognize the device?
> I've changed USB ports, changed iPhones, and it hasn't been recognized.

Having the same issue here.. iPhone 6S, iOS 14.0

**Comment by franesh** [comment]
> What should I do if bootrain does not recognize the device?
> I've changed USB ports, changed iPhones, and it hasn't been recognized.

Same here ... i tried everything ... it hasnt been recognized ... btw i got Ipad pro 12.9 1st gen

**Comment by JesseB0rn** [comment]
Same

**Comment by ImranDoet** [comment]
Sadly, the only fix for recognizing ur phone is to use something other than bootra1n as it seems to have difficulties with some phones. Use checkn1x and Etcher (to flash the iso, you MUST use this, it doesn't work with rufus, I tried). It's more lightweight and it worked for me

**Comment by DEALWITHIT199** [comment]
> What should I do if bootrain does not recognize the device?
> I've changed USB ports, changed iPhones, and it hasn't been recognized.

Use a high quality cable

**Comment by DEALWITHIT199** [comment]
> What should I do if bootrain does not recognize the device?
> I've changed USB ports, changed iPhones, and it hasn't been recognized.

if still getting errors... did you connect to USB 2.0 slot?

**Comment by DEALWITHIT199** [comment]
Hi guys... I'm gonna close this comment and thank you for the ones who helped getting my iPhone 14.0 jailbreak with bootra1n 0.11.0. Thank you!

**Comment by JesseB0rn** [comment]
> > What should I do if bootrain does not recognize the device?
> > I've changed USB ports, changed iPhones, and it hasn't been recognized.
> 
> Use a high quality cable

I used the OG apple cable. It seems to be a problem with BIOS based systems

**Comment by DEALWITHIT199** [comment]
> > > What should I do if bootrain does not recognize the device?
> > > I've changed USB ports, changed iPhones, and it hasn't been recognized.
> > 
> > 
> > Use a high quality cable
> 
> I used the OG apple cable. It seems to be a problem with BIOS based systems

The problem is not the BIOS Based system. its bootra1n 0.11.0 version itself, it has alot of bugs and its beta means work in progress, so better to use Checkn1x first.
